// 初始單字資料 — 學測常見 50 字
// 涵蓋 Level 1-3,適合升高一學生
const WORDS_DATA = [
  { id: 1,  english: "happy",         chinese: "快樂的、高興的",       pos: "adj.",  example: "She felt happy after the test.",                 translation: "考試後她感到很開心。",     level: 1 },
  { id: 2,  english: "friend",        chinese: "朋友",                 pos: "n.",    example: "He is my best friend.",                          translation: "他是我最好的朋友。",       level: 1 },
  { id: 3,  english: "school",        chinese: "學校",                 pos: "n.",    example: "I go to school by bus.",                         translation: "我搭公車上學。",           level: 1 },
  { id: 4,  english: "teacher",       chinese: "老師",                 pos: "n.",    example: "Our English teacher is very kind.",              translation: "我們的英文老師很親切。",   level: 1 },
  { id: 5,  english: "study",         chinese: "研讀、學習",           pos: "v.",    example: "I study English every day.",                     translation: "我每天讀英文。",           level: 1 },
  { id: 6,  english: "learn",         chinese: "學習、得知",           pos: "v.",    example: "Children learn fast.",                           translation: "小孩學得快。",             level: 1 },
  { id: 7,  english: "write",         chinese: "書寫、寫作",           pos: "v.",    example: "Please write your name here.",                   translation: "請在這裡寫下你的名字。",   level: 1 },
  { id: 8,  english: "think",         chinese: "思考、認為",           pos: "v.",    example: "I think you are right.",                         translation: "我認為你是對的。",         level: 1 },
  { id: 9,  english: "read",          chinese: "閱讀",                 pos: "v.",    example: "She likes to read novels.",                      translation: "她喜歡看小說。",           level: 1 },
  { id: 10, english: "beautiful",     chinese: "美麗的",               pos: "adj.",  example: "What a beautiful day!",                          translation: "多美好的一天啊!",          level: 1 },
  { id: 11, english: "believe",       chinese: "相信",                 pos: "v.",    example: "I believe in you.",                              translation: "我相信你。",               level: 2 },
  { id: 12, english: "important",     chinese: "重要的",               pos: "adj.",  example: "Health is the most important thing.",            translation: "健康是最重要的事。",       level: 2 },
  { id: 13, english: "different",     chinese: "不同的",               pos: "adj.",  example: "We have different opinions.",                    translation: "我們有不同的意見。",       level: 2 },
  { id: 14, english: "example",       chinese: "例子、範例",           pos: "n.",    example: "Can you give me an example?",                    translation: "你能舉個例子嗎?",          level: 2 },
  { id: 15, english: "language",      chinese: "語言",                 pos: "n.",    example: "English is an international language.",          translation: "英文是國際語言。",         level: 2 },
  { id: 16, english: "provide",       chinese: "提供",                 pos: "v.",    example: "The hotel provides free breakfast.",             translation: "飯店提供免費早餐。",       level: 2 },
  { id: 17, english: "develop",       chinese: "發展、開發",           pos: "v.",    example: "Children develop quickly.",                      translation: "孩子發展得很快。",         level: 2 },
  { id: 18, english: "environment",   chinese: "環境",                 pos: "n.",    example: "We must protect the environment.",               translation: "我們必須保護環境。",       level: 2 },
  { id: 19, english: "communicate",   chinese: "溝通、交流",           pos: "v.",    example: "We communicate by email.",                       translation: "我們用電子郵件溝通。",     level: 2 },
  { id: 20, english: "delicious",     chinese: "美味的",               pos: "adj.",  example: "This cake is delicious.",                        translation: "這蛋糕很好吃。",           level: 2 },
  { id: 21, english: "achieve",       chinese: "達成、實現",           pos: "v.",    example: "She achieved her goal.",                         translation: "她達成了目標。",           level: 3 },
  { id: 22, english: "analyze",       chinese: "分析",                 pos: "v.",    example: "Scientists analyze data carefully.",             translation: "科學家仔細分析資料。",     level: 3 },
  { id: 23, english: "benefit",       chinese: "好處、獲益",           pos: "n.",    example: "Exercise has many benefits.",                    translation: "運動有許多好處。",         level: 3 },
  { id: 24, english: "challenge",     chinese: "挑戰",                 pos: "n.",    example: "Learning English is a challenge.",               translation: "學英文是個挑戰。",         level: 3 },
  { id: 25, english: "consider",      chinese: "考慮、認為",           pos: "v.",    example: "Please consider my offer.",                      translation: "請考慮我的提議。",         level: 3 },
  { id: 26, english: "encourage",     chinese: "鼓勵",                 pos: "v.",    example: "My parents encourage me to read.",               translation: "我父母鼓勵我閱讀。",       level: 3 },
  { id: 27, english: "experience",    chinese: "經驗、體驗",           pos: "n.",    example: "He has rich teaching experience.",               translation: "他有豐富的教學經驗。",     level: 3 },
  { id: 28, english: "influence",     chinese: "影響",                 pos: "v./n.", example: "Movies influence young people.",                 translation: "電影影響年輕人。",         level: 3 },
  { id: 29, english: "opportunity",   chinese: "機會",                 pos: "n.",    example: "Don't miss this opportunity.",                   translation: "別錯過這個機會。",         level: 3 },
  { id: 30, english: "recognize",     chinese: "認出、辨識",           pos: "v.",    example: "I didn't recognize you at first.",               translation: "我一開始沒認出你。",       level: 3 },
  { id: 31, english: "determine",     chinese: "決定、決心",           pos: "v.",    example: "She determined to win.",                         translation: "她決心要贏。",             level: 3 },
  { id: 32, english: "essential",     chinese: "必要的、基本的",       pos: "adj.",  example: "Water is essential for life.",                   translation: "水是生命的必需品。",       level: 3 },
  { id: 33, english: "necessary",     chinese: "必要的",               pos: "adj.",  example: "Sleep is necessary for health.",                 translation: "睡眠對健康是必要的。",     level: 3 },
  { id: 34, english: "participate",   chinese: "參與、參加",           pos: "v.",    example: "All students participated in the event.",        translation: "所有學生都參加了活動。",   level: 3 },
  { id: 35, english: "perspective",   chinese: "觀點、看法",           pos: "n.",    example: "Try a different perspective.",                   translation: "試試不同的觀點。",         level: 3 },
  { id: 36, english: "significant",   chinese: "重要的、顯著的",       pos: "adj.",  example: "This is a significant discovery.",               translation: "這是個重大發現。",         level: 3 },
  { id: 37, english: "tradition",     chinese: "傳統",                 pos: "n.",    example: "It is a family tradition.",                      translation: "這是家族傳統。",           level: 3 },
  { id: 38, english: "various",       chinese: "各種的、不同的",       pos: "adj.",  example: "The shop sells various items.",                  translation: "這家店賣各種商品。",       level: 3 },
  { id: 39, english: "understand",    chinese: "了解、理解",           pos: "v.",    example: "Do you understand the question?",                translation: "你了解這問題嗎?",          level: 2 },
  { id: 40, english: "successful",    chinese: "成功的",               pos: "adj.",  example: "She is a successful writer.",                    translation: "她是個成功的作家。",       level: 2 },
  { id: 41, english: "interesting",   chinese: "有趣的",               pos: "adj.",  example: "This book is very interesting.",                 translation: "這本書很有趣。",           level: 1 },
  { id: 42, english: "accommodate",   chinese: "容納、提供住宿",       pos: "v.",    example: "The hall can accommodate 500 people.",           translation: "這大廳可容納 500 人。",    level: 4 },
  { id: 43, english: "embarrass",     chinese: "使尷尬",               pos: "v.",    example: "Don't embarrass me in public.",                  translation: "別在公開場合讓我尷尬。",   level: 4 },
  { id: 44, english: "occasionally",  chinese: "偶爾",                 pos: "adv.",  example: "We occasionally eat out.",                       translation: "我們偶爾外出用餐。",       level: 4 },
  { id: 45, english: "privilege",     chinese: "特權、榮幸",           pos: "n.",    example: "It is a privilege to meet you.",                 translation: "認識你是我的榮幸。",       level: 4 },
  { id: 46, english: "recommend",     chinese: "推薦、建議",           pos: "v.",    example: "I recommend this restaurant.",                   translation: "我推薦這家餐廳。",         level: 3 },
  { id: 47, english: "responsibility",chinese: "責任",                 pos: "n.",    example: "Take responsibility for your actions.",          translation: "為你的行為負責。",         level: 3 },
  { id: 48, english: "rhythm",        chinese: "節奏、韻律",           pos: "n.",    example: "Dance to the rhythm of music.",                  translation: "隨著音樂的節奏跳舞。",     level: 4 },
  { id: 49, english: "tomorrow",      chinese: "明天",                 pos: "n./adv.", example: "See you tomorrow.",                            translation: "明天見。",                 level: 1 },
  { id: 50, english: "knowledge",     chinese: "知識",                 pos: "n.",    example: "Knowledge is power.",                            translation: "知識就是力量。",           level: 2 },
];

if (typeof module !== "undefined") module.exports = WORDS_DATA;
